// build.js — runs as the Render "Build Command" for this static site.
// Reads FIRESTORE_STATUS_URL and POSTGRES_ADMIN_URL from the environment
// and writes them into config.js, which index.html loads before app.js.
// No dependencies, no network calls — just a file write.

const fs = require('fs');
const path = require('path');

const FIRESTORE_STATUS_URL =
  process.env.FIRESTORE_STATUS_URL ||
  'https://debtposinterprise-database-backup.onrender.com/status';

const POSTGRES_ADMIN_URL =
  process.env.POSTGRES_ADMIN_URL ||
  'https://marniestore-debtpos-postgre-aiven-backup.onrender.com/admin';

const contents =
  '// Generated by build.js at deploy time — do not edit by hand.\n' +
  'window.APP_CONFIG = ' + JSON.stringify({ FIRESTORE_STATUS_URL, POSTGRES_ADMIN_URL }, null, 2) + ';\n';

fs.writeFileSync(path.join(__dirname, 'config.js'), contents);

console.log('config.js written with:');
console.log('  FIRESTORE_STATUS_URL =', FIRESTORE_STATUS_URL);
console.log('  POSTGRES_ADMIN_URL   =', POSTGRES_ADMIN_URL);
